config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'
  get 'about' => 'about#index'

  get '/signup' => 'users#new'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  delete '/signout' => 'sessions#destroy'

  get 'auth/facebook/callback' => 'sessions#create'
  get 'auth/github/callback' => 'sessions#create'

  get '/search' => 'meals#search'

  resources :charts do 
    resources :meals, only: [:new, :show, :index]
  end

  resources :meals
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
    scope :most_recent, -> {order("created_at desc")}
    has_many :meals, dependent: :destroy
    has_many :users, through: :meals

    validates :date, :time, presence: true

    def normalize_date
        date.strftime("%B %d, %Y")
    end

    def normalize_time
        time.strftime("%I:%M %p")
    end
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :chart, optional: true

    validates :meal_name, presence: true, format: { with: /\A[a-zA-Z\s]+\z/, message: "only allows letters" }

     scope :meals_by_meal_type, -> (name) {where(meal_type: name)}
     scope :meals_by_user, -> (name) {where(user_id: name)}
     scope :by_user, -> (name) {Meal.joins(:user).where("name = ?", name)}    
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    has_many :meals, dependent: :destroy
    has_many :charts, through: :meals

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, length: { in: 6..20 }

    def self.find_or_create_by_omniauth(auth)
        oauth_email = auth["info"]["email"]
        self.where(:email => oauth_email).first_or_create do |user|
            user.password = SecureRandom.hex(10)
            user.name = auth["info"]["name"] || auth["info"]["nickname"]
        end
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
        
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :require_logged_in
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_logged_in
        redirect_to signin_path, alert: "You must sign in first." unless logged_in?
    end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
    include SetChart
    before_action :require_logged_in
    before_action only: [:show, :edit, :update, :destroy] do
        set_chart(params[:id])
    end

    
    def index   
        @charts = Chart.most_recent   
    end

    def search
        if params[:search].blank?  
            redirect_to(root_path, alert: "Empty field!")
        else  
            @charts = Chart.search(params[:search])
        end  
    end
    
    def new
        @chart = Chart.new
    end
    
    def show
    end
    
    def create
        @chart = Chart.new(chart_params)
        if @chart.save
            redirect_to chart_path(@chart), notice: "Successfully created a chart."
        else
            render :new
        end
    end

    def edit
        if @chart.users.first && current_user.name != @chart.users.first.name
            redirect_to charts_path, alert: "You don't have access to edit this chart."
        end
    end

    def update
        if @chart.update(chart_params) 
            redirect_to charts_path
        else
            render :edit
        end
    end

    def destroy
        @chart.destroy
        redirect_to charts_path   
    end

    private

    def chart_params
        params.require(:chart).permit(:date, :time)
    end   
end

app/controllers/concerns/set_chart.rb
module SetChart
    def set_chart(params)
        redirect_to root_path, alert: "Chart not found" unless @chart = Chart.find_by(id: params)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    include SetChart
    before_action :require_logged_in
    before_action :set_meal, only: [:show, :edit, :update, :destroy]
    before_action only: [:new] do
        set_chart(params[:chart_id])
    end
    
    
    def index
        if params[:chart_id].present?
            if @chart = Chart.find_by(id: params[:chart_id])
                @meals = @chart.meals
            else
                redirect_to charts_path, alert:"Chart not found"
            end
        else
            @meals = Meal.all
        end
    end

    def new
        # @chart = Chart.find_by(id: params[:chart_id])
        @meal = @chart.meals.build
    end

    def search
        @meals = Meal.meals_by_meal_type(params[:q]).meals_by_user(current_user)
        if @meals.empty?
            @meals = Meal.by_user(params[:q])
        end
    end

    def show
    end

    def create
        @meal = Meal.new(meal_params)
        if @meal.save
            redirect_to chart_meals_path(@meal.chart)
        else
            render :new
        end
    end

    def edit
        if current_user.name != @meal.user.name
            redirect_to chart_meals_path(@meal.chart),
            alert: "You don't have access to edit this meal."
        end
    end

    def update
        if @meal.update(meal_params) 
            redirect_to chart_meals_path(@meal.chart)
        else
            render :edit
        end
    end

    def destroy 
        @meal.destroy
        redirect_to chart_meals_path(@meal.chart)
    end

    private

    def meal_params
        params.require(:meal).permit(:meal_name, :meal_type, :note, :chart_id, :user_id)
    end

    def set_meal
        redirect_to root_path, alert: "Meal not found" unless @meal = Meal.find_by(id: params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        if auth = request.env["omniauth.auth"]
            @user = User.find_or_create_by_omniauth(auth)
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            @user = User.find_by(email: params[:user][:email])
            if @user && @user.authenticate(params[:user][:password])
                session[:user_id] = @user.id
                redirect_to user_path(@user)
            else
                redirect_to signin_path,
                alert: "Invalid email or password. Please try again."
            end
        end
    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, except: [:new, :create]
    
    def new
       @user = User.new 
    end

    def show
        @user = User.find_by(id: params[:id])
        if @user.nil?
            redirect_to root_path, alert: "User not found"
        elsif
            current_user != @user
            redirect_to root_path,
            alert: "This account doesn't belongs to you."
        else
            @user
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save  
            session[:user_id] = @user.id
            redirect_to user_path(@user),
            notice: "You have successfully created an account"
        else
            render :new 
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
    
end

app/helpers/meals_helper.rb
module MealsHelper
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/_about.html.erb
<div class="container">
    <h5>About Us</h5>
    <pre class="pre-scrollable">
        <p>  Bites for Tikes app is built for busy parents, 
        
        who struggle to plan meals for their kids on an everyday basis. 
        
        This app will let you make a Chart for each day and plan breakfast, 
        
        lunch and dinner in advance. 
        
        This way you don’t have to rush each 
        
        morning to decide what you are going to make today? </p>

        <p>  Our purpose is to make each one of your lives a little easier and more organized.
        
        It's very easy to use. 
        
        You can simply sign up or sign in(if you already signed up) 
        
        and create a chart for a particular day then add meals for that day. 
        
        You can track all of your meals and charts you have created.</p>  
    </pre>
    <div class="row">
        <div class="col-sm-3">
            <div class="img">
                <%= image_tag(("meal-plan.jpg"), class:"img-about")%>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="img">
                <%= image_tag(("baby1.jpg"), class:"img-about")%>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="img">
                <%= image_tag(("food1"), class:"img-about")%>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="img">
                <%= image_tag(("babyfood.jpg"), class:"img-about")%>
            </div>
        </div>
    </div> 
</div>

app/views/about/index.html.erb
<%= render "about" %>

app/views/charts/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @chart} %>
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body", style="background-color: beige;">
            <h2>Chart Form</h2> 
            <%= form_for @chart do |f| %>
                <%= f.label :date %>
                <%= f.date_field :date, min: Date.current %>
                <hr>
                <%= f.label :time %>
                <%= f.time_field :time %>
                <hr>
                <%= f.submit class:"btn btn-success"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charts/edit.html.erb
<%= render 'form'%>
<div class="container">
    <%= link_to "Go Back", charts_path,class:"btn btn-info"%>
</div>

app/views/charts/index.html.erb
<div class="container">
    <table class="table table-hover">
        <thead>
            <tr class="table-danger">
                <th>Date</th>
                <th>Day</th>
                <th>Time</th>
                <th>Show</th>
                <th>Edit</th>
                <th>Remove</th>
                <th>Creator</th>
            </tr>
        </thead>
        <tbody>
        <% @charts.each do |chart| %>
            <tr class="table-info">
                <td><%= chart.normalize_date %></td>
                <td><%= chart.date.strftime("%A") %></td>
                <td><%= chart.normalize_time %></td>
                <td><%= link_to 'Show', chart_path(chart)%></td>
                <%if chart.users.first == current_user %> 
                    <td><%= link_to 'Edit', edit_chart_path(chart)%></td>
                    <td><%= link_to 'X', chart_path(chart), method: :delete, data: { confirm: 'Are you sure?'}, class:"btn-danger"%></td>
                <%else%>
                    <td></td>
                    <td></td>
                <%end%>
                <%if chart.users.first %>
                    <td>Created By, <%= chart.users.first.name %></td>
                <% else %>
                    <td></td>
                <% end %>
            </tr>
        <% end %>
        </tbody>
    </table>
    <%= link_to "Create an another Chart", new_chart_path, class:"btn btn-success" %>
</div>

app/views/charts/new.html.erb
<%= render "form" %>
<div class="container">
    <%= link_to "Go Back", user_path(current_user),class:"btn btn-info"%>
</div>

app/views/charts/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body", style="background-color: beige;">
            <p>Date: <%= @chart.normalize_date %></p>
            <hr>
            <p>Day: <%= @chart.date.strftime("%A") %></p>
            <hr>
            <p>Time: <%= @chart.normalize_time %></p>
            <hr>
            <h5> Click below to </h5>
            <hr>
            <p>
                <%= link_to "Go Back", new_chart_path,class:"btn btn-info"%> |
                <%= link_to 'Add Meals', new_chart_meal_path(@chart), class:"btn btn-success"%> | 
                <%= link_to 'Go to Menu', chart_meals_path(@chart), class:"btn btn-success"%>  
            </p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_errors.html.erb
<div class="field_with_errors", style="text-align:center; color:red;">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <% if object && object.errors.any? %>
      <div id="error_explanation"> 
        <% object.errors.full_messages.each do |msg| %>
          <%= msg %>
          <br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash_mesg.html.erb
<div class="col-sm-9 col-md-7 col-lg-5 mx-auto", style="color:red; text-align:center;">
  <% if flash[:alert] %>
    <%= flash[:alert] %>
  <% end %>
</div>
<div class="container", style="color:green; text-align:center;">
  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
  <div class="container">
    <footer class="pt-4 mb-0" role='alert'>
      <p>Copyright © Bites for Tikes 2020</p>
    </footer>
  </div>

app/views/layouts/_links.html.erb
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BitesForTikes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render partial: 'layouts/links'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('meal-plan.jpg') %>
  </head>

  <body>
    <%= render partial: 'partials/title'%>
    <%= render partial: 'partials/navbar' %>
    <%= render partial: "layouts/errors", locals: {object: @user} %>
    <%= render partial: "layouts/flash_mesg" %>
    
    <%= yield %>

    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= render partial: "layouts/errors", locals: {object: @meal} %>
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body", style="background-color: beige;">
            <%= form_for @meal do |f| %>

            <%= f.hidden_field :chart_id, value: @meal.chart.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>

            <%= f.label :meal_name %>
            <%= f.text_field :meal_name %>
            <hr>
            <%= f.label :meal_type %>
            <%= f.select(:meal_type, options_for_select([['Breakfast', 'Breakfast'],['Lunch', 'Lunch'],['Dinner', 'Dinner']])) %>
            <hr>
            <%= f.label :note %>
            <%= f.text_area :note %>
            <hr>
            <%= f.submit class: "btn btn-success"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/meals/_index.html.erb
<table class="table table-hover">
    <thead>
        <tr class="table-danger">       
            <th>Meal type</th>
            <th>Name</th>
            <th>Note</th>
            <th>Creator</th>
        </tr>
    </thead>
    <tbody>
        <% @meals.each do |meal| %>
            <tr class="table-info">
                <td><%= meal.meal_type %></td>
                <td><%= meal.meal_name %></td>
                <td><%= meal.note %></td>
                <%if meal.user %>
                    <td>Created By, <%= meal.user.name %></td>
                <% else %>
                    <td></td>
                <% end %>
            </tr>
        <% end %>
    </tbody>
</table>
<br>

app/views/meals/edit.html.erb
<%= render 'form' %>
<div class="container">
    <%= link_to "Go Back", chart_meals_path(current_user),class:"btn btn-info"%>
</div>

app/views/meals/index.html.erb
<div class="container">
    <% if @chart %>
    <h3>Here is <%= @chart.date.strftime("%A") %>'s menu</h3>
        <table class="table table-hover">
            <thead>
            <tr class="table-danger">
                <th>Meal type</th>
                <th>Name</th>
                <th>Note</th>
                <th>Edit</th>
                <th>Remove</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <% @meals.each do |meal| %>
            <tr class="table-info">
                    <td><%= meal.meal_type %></td>
                    <td><%= meal.meal_name %></td>
                    <td><%= meal.note %></td>
                    <%if meal.user == current_user %> 
                        <td><%= link_to 'Edit', edit_meal_path(meal)%></td>
                        <td><%= link_to 'X',meal_path(meal), method: :delete, data: { confirm: 'Are you sure?'}, class:"btn-danger" %></td>
                    <%else%>
                        <td></td>
                        <td></td>
                    <%end%>
                    <%if meal.user %>
                        <td>Created By, <%= meal.user.name %></td>
                    <% else %>
                        <td></td>
                    <% end %>
                </tr>
            <% end %>
            </tbody>
        </table>
        <%= link_to 'Create Another Meal', new_chart_meal_path(@chart), class:"btn btn-success" %>
        <br/><br/>
        <%= link_to "Go Back", chart_path(@chart),class:"btn btn-info"%>
    <%else%>
        <%= render "index" %>
    <% end %>
</div>
           
            
            

app/views/meals/new.html.erb
<%= render 'form'%>
<div class='container'>
    <%= link_to "Go Back", chart_path(current_user),class:"btn btn-info"%>
</div>

app/views/meals/search.html.erb
<div class="container">
    <p>Search result</p>
    <%= render 'index'%>
</div>

app/views/meals/show.html.erb
<div class="container">
  <table class="table table-hover">
    <thead>
      <tr class="table-danger">
        <th>Meal type</th>
        <th>Name</th>
        <th>Note</th>
      </tr>
    </thead>
    <tbody>
      <tr class="table-info">
        <td><%= @meal.meal_type %></td>
        <td><%= @meal.meal_name %></td>
        <td><%= @meal.note%></td>
      </tr>          
    </tbody>
  </table>
</div>

app/views/partials/_footer.html.erb
  <div class="container">
    <footer class="fixed-bottom pt-4 mb-0 alert alert-primary" role='alert'>
      <p>Copyright © Bites for Tikes 2020</p>
    </footer>
  </div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item px-lg-4">
              <%= link_to 'Home', root_path, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
              <%= link_to 'About', about_path, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <% if logged_in? %>
          <li class="nav-item px-lg-4">
              <%= link_to 'Charts',charts_path, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
              <%= link_to 'Meals',meals_path, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
              <%= link_to 'Sign Out', signout_path, method: :delete, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <li class="user-name">
            Hi <%= link_to current_user.name, user_path(current_user), class:"text-dark"%>!
          </li>
          <% else %>
          <li class="nav-item px-lg-4">
              <%= link_to 'Sign In', signin_path, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
              <%= link_to 'Sign Up', signup_path, class:"nav-link text-uppercase text-expanded" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav> 

app/views/partials/_signin.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center">Sign In</h5>
            <div class="form-signin">
              <%= form_for @user, url: signin_path  do |f|%>
                  <div class="form-label-group">
                    <%= f.email_field :email, placeholder: "Email address", class: "form-control", id: "inputEmail", required: true %>
                    <%= f.label :email, for: "inputEmail" %>
                  </div>
                  <div class="form-label-group">
                    <%= f.password_field :password, placeholder: "password", class: "form-control", id: "inputPassword", required: true %>
                    <%= f.label :password, for: "inputPassword" %>
                  </div>           
                  <%= f.submit "Sign In", class:"btn btn-lg btn-primary btn-block text-uppercase"%>           
                  <hr class="my-4">
                  <%= link_to ('<i class="fab fa-github mr-2"></i> Sign in with Github').html_safe, "/auth/github", class:"btn btn-lg btn-danger btn-block text-uppercase" %>
                  <%= link_to ('<i class="fab fa-facebook-f mr-2"></i> Sign in with Facebook').html_safe, "/auth/facebook", class:"btn btn-lg btn-facebook btn-primary btn-block text-uppercase" %>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partials/_signup.html.erb
<div class="container" style="width:60%;">
  <div class="row">
    <div class="col-lg-10 col-xl-9 mx-auto">
      <div class="card card-signin flex-row my-5">
        <div class="card-img-left d-none d-md-flex">
        </div>
          <div class="card-body">
            <h5 class="card-title text-center">Sign Up</h5>
            <div class="form-signin">  
              <%= form_for @user do |f|%>
                <div class="form-label-group">
                    <%= f.text_field :name, placeholder: "Username", autofocus: true, class: "form-control", id: "inputUsername", required: true  %>
                    <%= f.label :Username, for: "inputUsername" %>
                </div> 
                <hr>
                <div class="form-label-group">
                    <%= f.email_field :email, placeholder: "Email address", class: "form-control", id: "inputEmail", required: true %>
                    <%= f.label :email, for: "inputEmail" %>
                </div>                 
                <hr>
                <div class="form-label-group">
                    <%= f.password_field :password, placeholder: "password", class: "form-control", id: "inputPassword", required: true %>
                    <%= f.label :password, for: "inputPassword" %>
                </div>                        
                <hr>
                <div class="form-label-group">
                    <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control", id: "inputConfirmPassword", required: true %>
                    <%= f.label :Confirm_password, for: "inputConfirmPassword" %>
                </div>
                <hr>
                <%= f.submit "Sign Up", class:"btn btn-lg btn-primary btn-block text-uppercase"%>   
              <% end %>
              <hr class="my-4">
              <%= link_to ('<i class="fab fa-github mr-2"></i> Sign in with Github').html_safe, "/auth/github", class:"btn btn-lg btn-danger btn-block text-uppercase" %>
              <%= link_to ('<i class="fab fa-facebook-f mr-2"></i> Sign in with Facebook').html_safe, "/auth/facebook", class:"btn btn-lg btn-facebook btn-primary btn-block text-uppercase" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
                
  

app/views/partials/_title.html.erb
<h1 class="site-heading text-center text-white d-none d-lg-block">
    <%= image_tag("meal-plan.jpg", alt:"Logo", style:"width:60px;")%>
    <span>Bites for Tikes</span>
</h1>
<p class="small">Meals planner for children</p>
<div class="container d-flex justify-content-center">
    <%= form_tag(search_path, method: 'get') do %>
        <%= text_field_tag :q %>
        <%= submit_tag 'Q', class: "btn-success" %>
    <% end %>
</div>

app/views/partials/_userInfo.html.erb
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body", style="background-color: beige;">
            <h1> Hello, <%= @user.name %></h1>
            Click below to create a new Chart 
            <br><hr>
            <%= link_to "Create a new Chart", new_chart_path, class:"btn btn-success" %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/users/new.html.erb
<%= render partial: "partials/signup" %>  

app/views/users/show.html.erb
<%= render partial: "partials/userInfo" %>

app/views/welcome/home.html.erb
<%= image_tag('TP09_WEB_SOLIDFOOD_.jpg', width:"50%", class: "mx-auto d-block") %>